### PR TITLE
Upgrading ruby and dependencies

### PR DESCRIPTION
**Pull request by tbenett**
A year has passed. It was time to remove the dust of this project and to **upgrade the stack**.

### CODE REVIEW

**Comment by andrew** [comment]
👍

**Comment by andrew** [comment]
You can also use `gemspec` in the Gemfile to pull in dependencies from the projects gemspec rather than having to declare them twice, as mentioned here: 
https://bundler.io/v1.12/guides/creating_gem.html

**Comment by tbenett** [comment]
Ah nice @andrew thanks a lot for bringing that to me. Thus, I will update this PR using that method. 

Two things though:
- should I remove dependencies from Gemfile entirely then?
- should I remove gemfile entirely?

**Comment by andrew** [comment]
The Gemfile is still useful as it allows bundler to pull in all the dependencies without needing to build the gem. I'd suggest moving all the dependencies required for development and testing to the gemspec as `add_development_dependency` and slimming down the Gemfile to just:

```
source "https://rubygems.org"

gemspec
```

Examples from one of my other gems:

https://github.com/splitrb/split/blob/master/split.gemspec
https://github.com/splitrb/split/blob/master/Gemfile

**Pull request merged**
